---
services:
  oxidized:
    container_name: oxidized
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - 83:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - ./:/home/oxidized/.config/oxidized/
