---
services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_UPLOAD=5000
    volumes:
      - ./appdata/.config:/config
      - ./appdata/.data:/data
    ports:
      - 97:80
    restart: unless-stopped
  mysql:
    container_name: projectsend_db
    hostname: mariadb
    restart: unless-stopped
    image: mariadb:10.7
    volumes:
      - ./appdata/.db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: E4fBaS4utfMjAX
      MYSQL_DATABASE: projectsend
      MYSQL_USER: projectsend
      MYSQL_PASSWORD: E4fBaS4utfMjAX