ervices:
  nginx:
    image: nginx:latest
    container_name: nginx_front
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/cert/cert.pem
      - ./ssl/server.key:/etc/nginx/cert/server.key
    network_mode: host
