---
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LOG_TO_STDOUT= #optional
    volumes:
      - ./conf.d:/config
      - ./logs:/var/log
    ports:
      - 5514:5514/udp
      - 5514:5514/tcp
    restart: unless-stopped